import os
import time
import json
import random
import logging
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlsplit, quote

logger = logging.getLogger("proxy_manager")


class AllProxyGroupsExhaustedError(Exception):
    """Raised when all configured proxy groups are exhausted (e.g. 402 Payment Required)."""
    pass


BASE_DIR = Path(__file__).resolve().parent
PROXIES_FILE = BASE_DIR / "proxies.txt"
RESIDENTIAL_PROXIES_FILE = BASE_DIR / "proxies_residential.txt"
EXHAUSTED_GROUPS_FILE = BASE_DIR / ".exhausted_proxy_groups.json"
EXHAUSTION_TTL_SECONDS = 24 * 3600  # 24 hours

# Per-proxy quarantine ("bench") for the SCOUTER's datacenter pool only. Complements the
# per-ACCOUNT exhaustion above (which can't help here: 191 proxies share one account).
QUARANTINE_FILE = BASE_DIR / ".proxy_quarantine.json"
PROXY_STRIKE_LIMIT = 3               # consecutive proxy-specific failures before a proxy is benched
QUARANTINE_MAX_FRACTION = 0.25       # never bench more than this share of the pool
# Bench length grows each time the same proxy is benched again without a success in between:
# 2, 3, 5, then 10 days (cap) -- the user's call 2026-10-04, since CROUS blocks last long.
# After each bench the proxy gets ONE more chance (probation). Why growing: CROUS-side blocks
# last days -- 9 proxies still blocked 9 days on -- and every retry of a blocked proxy is a
# ~12 s timeout on that check, while Marseille rooms are gone in 20-30 s. The old fixed 24 h
# bench retried them daily forever. Any success resets everything.
BENCH_DURATIONS_SECONDS = (2 * 86400, 3 * 86400, 5 * 86400, 10 * 86400)
QUARANTINE_TTL_SECONDS = BENCH_DURATIONS_SECONDS[0]   # first bench (kept for existing callers/tests)


def bench_duration_seconds(bench_count) -> int:
    """How long the Nth consecutive bench of the same proxy lasts (1-based, capped)."""
    try:
        n = max(1, int(bench_count))
    except (TypeError, ValueError):
        n = 1
    return BENCH_DURATIONS_SECONDS[min(n, len(BENCH_DURATIONS_SECONDS)) - 1]


def format_duration(seconds: float) -> str:
    """'25 min' / '24h' / '2 jours' -- for logs and Telegram."""
    if seconds < 3600:
        return f"{max(1, round(seconds / 60))} min"
    days = seconds / 86400
    return f"{round(seconds / 3600)}h" if days < 2 else f"{round(days)} jours"


_CURRENT_INDEX = 0


def _parse_proxies_file(path: Path) -> list[str]:
    """Parse a host:port:user:pass (or full URL) proxy list file into http://user:pass@host:port URLs."""
    proxies = []
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("http://") or line.startswith("https://") or line.startswith("socks5://"):
                proxies.append(line)
            else:
                parts = line.split(":", 3)
                if len(parts) == 4:
                    host, port, user, pwd = parts
                    user_enc = quote(user, safe="")
                    pwd_enc = quote(pwd, safe="")
                    proxies.append(f"http://{user_enc}:{pwd_enc}@{host}:{port}")
                elif len(parts) == 2:
                    host, port = parts
                    proxies.append(f"http://{host}:{port}")

    seen = set()
    unique = []
    for p in proxies:
        if p not in seen:
            seen.add(p)
            unique.append(p)
    return unique


def load_proxies() -> list[str]:
    """
    Returns the SCOUTER's datacenter proxy pool as a list of proxy URLs in the form
    http://user:pass@ip:port. Loads from the CROUS_PROXY environment variable, proxies.txt
    (hand-managed entries: Oxylabs) and proxies_webshare.txt (the Webshare "Proxy Server"
    datacenter plan, generated by sync_webshare_proxies() -- never edit it by hand).
    """
    proxies = []
    env_proxy = os.getenv("CROUS_PROXY") or os.getenv("HTTPS_PROXY") or os.getenv("HTTP_PROXY")
    if env_proxy:
        proxies.append(env_proxy.strip())
    proxies.extend(_parse_proxies_file(PROXIES_FILE))
    proxies.extend(_parse_proxies_file(_webshare_proxies_file()))

    seen = set()
    unique = []
    for p in proxies:
        if p not in seen:
            seen.add(p)
            unique.append(p)
    return unique


def load_residential_proxies() -> list[str]:
    """
    Returns the AUTH + SNIPER residential proxy pool (proxies_residential.txt --
    Webshare "Static Residential" plan). Deliberately separate from load_proxies():
    auth (login) and the sniper (apply flow) need to look like a real human, which
    residential IPs do far better than datacenter ones; the scouter's bulk polling
    doesn't need that and stays on the cheap datacenter pool.
    """
    return _parse_proxies_file(RESIDENTIAL_PROXIES_FILE)


STATE_FILE = BASE_DIR / ".proxy_index"
SNIPER_STATE_FILE = BASE_DIR / ".sniper_proxy_index"
AUTH_STATE_FILE = BASE_DIR / ".auth_proxy_index"
AUTH_EXCLUDED_MARKERS = ("oxylabs",)      # proxies whose URL contains any marker are never used for auth
AUTH_PROXY_CHECK_TIMEOUT = 8              # seconds, per validation request


def _get_stored_index() -> int:
    if STATE_FILE.exists():
        try:
            return int(STATE_FILE.read_text().strip())
        except Exception:
            pass
    return 0


def _save_stored_index(idx: int):
    try:
        STATE_FILE.write_text(str(idx))
    except Exception:
        pass


def _get_sniper_stored_index() -> int:
    if SNIPER_STATE_FILE.exists():
        try:
            return int(SNIPER_STATE_FILE.read_text().strip())
        except Exception:
            pass
    return 0


def _save_sniper_stored_index(idx: int):
    try:
        SNIPER_STATE_FILE.write_text(str(idx))
    except Exception:
        pass


def _get_auth_stored_index() -> int:
    if AUTH_STATE_FILE.exists():
        try:
            return int(AUTH_STATE_FILE.read_text().strip())
        except Exception:
            pass
    return 0


def _save_auth_stored_index(idx: int):
    try:
        AUTH_STATE_FILE.write_text(str(idx))
    except Exception:
        pass



def get_proxy_group(proxy_url: str) -> str:
    """
    Extract provider account username from proxy URL to group proxies.
    Falls back to hostname or 'direct'.
    """
    if not proxy_url:
        return "direct"
    u = urlsplit(proxy_url)
    if u.username:
        import urllib.parse
        return urllib.parse.unquote(u.username)
    return u.hostname or "direct"


def get_exhausted_groups() -> dict[str, dict]:
    """
    Read .exhausted_proxy_groups.json, evict entries older than 24h TTL,
    and return dict of currently exhausted groups.
    Manual recovery: delete .exhausted_proxy_groups.json by hand (rm .exhausted_proxy_groups.json).
    """
    if not EXHAUSTED_GROUPS_FILE.exists():
        return {}
    try:
        content = EXHAUSTED_GROUPS_FILE.read_text(encoding="utf-8").strip()
        if not content:
            return {}
        data = json.loads(content)
        if not isinstance(data, dict):
            return {}
        now = time.time()
        active = {}
        changed = False
        for group, info in data.items():
            if isinstance(info, dict):
                exhausted_at = info.get("exhausted_at", 0)
                if (now - exhausted_at) < EXHAUSTION_TTL_SECONDS:
                    active[group] = info
                else:
                    changed = True
            else:
                changed = True
        if changed:
            try:
                EXHAUSTED_GROUPS_FILE.write_text(json.dumps(active, indent=2), encoding="utf-8")
            except Exception:
                pass
        return active
    except Exception as e:
        logger.warning(f"Failed to read exhausted proxy groups: {e}")
        return {}


def get_available_groups() -> list[str]:
    """Return distinct proxy groups loaded from proxies.txt that are not currently exhausted."""
    proxies = load_proxies()
    if not proxies:
        return []
    exhausted = get_exhausted_groups()
    all_groups = []
    seen = set()
    for p in proxies:
        g = get_proxy_group(p)
        if g not in seen:
            seen.add(g)
            all_groups.append(g)
    return [g for g in all_groups if g not in exhausted]


def mark_group_exhausted(group: str, reason: str = "402 Payment Required") -> bool:
    """
    Mark an entire proxy group as exhausted, persisting to .exhausted_proxy_groups.json.
    Returns True if this is a new transition (first time group is marked exhausted),
    or False if it was already marked exhausted.
    """
    if not group:
        return False
    current = get_exhausted_groups()
    is_new = group not in current
    now = time.time()
    iso = datetime.now(timezone.utc).isoformat()
    current[group] = {
        "exhausted_at": now,
        "iso": iso,
        "reason": reason
    }
    try:
        EXHAUSTED_GROUPS_FILE.write_text(json.dumps(current, indent=2), encoding="utf-8")
    except Exception as e:
        logger.error(f"Failed to write {EXHAUSTED_GROUPS_FILE}: {e}")
    return is_new


def proxy_key(proxy_url: str | None) -> str | None:
    """host:port only -- never credentials (this key is written to disk and shown in alerts)."""
    if not proxy_url:
        return None
    u = urlsplit(proxy_url)
    if not u.hostname:
        return None
    return f"{u.hostname}:{u.port}" if u.port else u.hostname


def _read_quarantine_state() -> dict:
    """
    Raw quarantine state {host:port: {"strikes": int, "quarantined_at": float | None, ...}}.
    Fails OPEN: any read/parse problem returns {} (nothing benched), so a corrupt or
    missing file can never shrink the pool or blind the scouter.
    """
    if not QUARANTINE_FILE.exists():
        return {}
    try:
        content = QUARANTINE_FILE.read_text(encoding="utf-8").strip()
        if not content:
            return {}
        data = json.loads(content)
        if not isinstance(data, dict):
            return {}
        return {k: v for k, v in data.items() if isinstance(k, str) and isinstance(v, dict)}
    except Exception as e:
        logger.warning(f"Failed to read proxy quarantine state (treating as empty): {e}")
        return {}


def _write_quarantine_state(state: dict) -> None:
    temp_file = QUARANTINE_FILE.with_suffix(".tmp")
    try:
        temp_file.write_text(json.dumps(state, indent=2), encoding="utf-8")
        temp_file.replace(QUARANTINE_FILE)
    except Exception as e:
        logger.error(f"Failed to write {QUARANTINE_FILE}: {e}")


def get_quarantined_proxies() -> dict[str, dict]:
    """
    Currently benched proxies, {host:port: info}. A bench lasts
    bench_duration_seconds(info["bench_count"]) (2, 3, 5, 10 days). When it ends the proxy
    goes on probation (strikes = limit - 1): ONE further proxy-specific failure re-benches
    it immediately, for longer; one success clears it fully. Manual recovery: delete
    .proxy_quarantine.json.
    """
    state = _read_quarantine_state()
    now = time.time()
    active = {}
    changed = False
    for key, info in state.items():
        quarantined_at = info.get("quarantined_at")
        if quarantined_at is None:
            continue
        ttl = bench_duration_seconds(info.get("bench_count", 1))
        try:
            age = now - float(quarantined_at)
        except (TypeError, ValueError):
            age = ttl  # unreadable timestamp -> treat as expired
        if age < ttl:
            active[key] = info
        else:
            info["quarantined_at"] = None
            info["strikes"] = PROXY_STRIKE_LIMIT - 1
            changed = True
    if changed:
        _write_quarantine_state(state)
    return active


def record_proxy_success(proxy_url: str | None) -> None:
    """A proxy that just worked is healthy: forget any strikes/bench it had."""
    key = proxy_key(proxy_url)
    if not key:
        return
    state = _read_quarantine_state()
    if key in state:
        del state[key]
        _write_quarantine_state(state)


def record_proxy_strike(proxy_url: str | None, reason: str = "") -> dict:
    """
    Record one proxy-specific failure (the caller only calls this when a DIFFERENT proxy
    then succeeded for the same request, so the fault is the proxy's, not a systemic
    outage). Strikes are consecutive (record_proxy_success resets them) and persisted.

    At PROXY_STRIKE_LIMIT the proxy is benched for QUARANTINE_TTL_SECONDS -- unless that
    would bench more than QUARANTINE_MAX_FRACTION of the pool, in which case it is NOT
    benched (blocked_by_floor) so this feature can never leave the scouter blind. With
    a very small pool the cap rounds down to 0, i.e. the feature is inert (fail-safe).

    Returns {"key", "strikes", "quarantined_now", "blocked_by_floor", "benched_count",
    "pool_size", "bench_count", "bench_seconds"} -- bench_count = how many times in a row
    this proxy has now been benched (1 = first time), bench_seconds = this bench's length.
    """
    key = proxy_key(proxy_url)
    pool_size = len(load_proxies())
    result = {"key": key, "strikes": 0, "quarantined_now": False, "blocked_by_floor": False,
              "benched_count": 0, "pool_size": pool_size, "bench_count": 0, "bench_seconds": 0}
    if not key:
        return result

    benched = get_quarantined_proxies()  # also applies TTL expiry before we read the state
    result["benched_count"] = len(benched)
    if key in benched:
        result["strikes"] = int(benched[key].get("strikes", PROXY_STRIKE_LIMIT))
        return result  # already benched -- nothing to add

    state = _read_quarantine_state()
    info = state.get(key, {})
    try:
        strikes = int(info.get("strikes", 0)) + 1
    except (TypeError, ValueError):
        strikes = 1
    info["strikes"] = min(strikes, PROXY_STRIKE_LIMIT)
    info["last_strike"] = datetime.now(timezone.utc).isoformat()
    info["last_reason"] = (reason or "")[:200]
    info.setdefault("quarantined_at", None)

    if strikes >= PROXY_STRIKE_LIMIT:
        if len(benched) >= int(pool_size * QUARANTINE_MAX_FRACTION):
            result["blocked_by_floor"] = True
        else:
            info["quarantined_at"] = time.time()
            try:
                info["bench_count"] = int(info.get("bench_count", 0)) + 1
            except (TypeError, ValueError):
                info["bench_count"] = 1
            result["quarantined_now"] = True
            result["benched_count"] = len(benched) + 1
            result["bench_count"] = info["bench_count"]
            result["bench_seconds"] = bench_duration_seconds(info["bench_count"])

    state[key] = info
    _write_quarantine_state(state)
    result["strikes"] = info["strikes"]
    return result


def bench_proxy(key: str, reason: str, bench_count: int = 1) -> None:
    """
    Bench a proxy by hand (host:port), as if it had just been benched for the
    bench_count-th time in a row: e.g. bench_count=4 -> 10 days, then probation. Used to
    keep proxies known to be blocked by CROUS out of rotation when the Webshare sync puts
    them back in the list (Webshare only checks that a proxy works, not that CROUS lets it in).
    """
    state = _read_quarantine_state()
    state[key] = {
        "strikes": PROXY_STRIKE_LIMIT,
        "last_strike": datetime.now(timezone.utc).isoformat(),
        "last_reason": (reason or "")[:200],
        "quarantined_at": time.time(),
        "bench_count": max(1, int(bench_count)),
    }
    _write_quarantine_state(state)


def get_current_proxy(rotate: bool = False, skip_exhausted: bool = True) -> str | None:
    """
    Get current active proxy URL, optionally rotating to next proxy in the list.
    When skip_exhausted=True, proxies belonging to exhausted groups AND individually
    quarantined proxies (see record_proxy_strike) are excluded.
    """
    proxies = load_proxies()
    if not proxies:
        return None

    if skip_exhausted:
        exhausted = get_exhausted_groups()
        benched = get_quarantined_proxies()
        candidates = [
            p for p in proxies
            if get_proxy_group(p) not in exhausted and proxy_key(p) not in benched
        ]
    else:
        candidates = proxies

    if not candidates:
        return None

    idx = _get_stored_index()
    if rotate:
        idx = (idx + 1) % 1_000_000
        _save_stored_index(idx)
    return candidates[idx % len(candidates)]


def rotate_proxy(skip_exhausted: bool = True) -> str | None:
    """Rotate to the next proxy in the list and return it."""
    return get_current_proxy(rotate=True, skip_exhausted=skip_exhausted)


def _sniper_candidate_list() -> list[str]:
    """
    Proxy ordering shared by get_sniper_proxy() and rotate_sniper_proxy(), so the
    same stored index always refers to the same proxy in both functions.

    Sources from the residential pool (load_residential_proxies()), not the
    scouter's datacenter pool -- the sniper's multi-page apply flow is exactly the
    kind of session where looking like a real human matters, which residential IPs
    do far better than datacenter ones. (Prior to 2026-09-25 this sourced from the
    datacenter pool with Webshare-first/Oxylabs-last ordering; that distinction is
    moot now since the residential pool has no Oxylabs entries at all.)

    NOTE: get_sniper_proxy() and rotate_sniper_proxy() used to index into two
    DIFFERENT orderings while sharing the same stored index -- meaning a rotation
    triggered by a 429 could land on essentially an arbitrary proxy, including
    possibly the one that just got rate-limited, wasting a request for nothing.
    Fixed 2026-09-25 by routing both through this single shared list.
    """
    return load_residential_proxies()


def rotate_sniper_proxy() -> dict | None:
    """Explicitly advances to the next sniper proxy and returns it."""
    candidate_list = _sniper_candidate_list()
    if not candidate_list:
        return None
    idx = (_get_sniper_stored_index() + 1) % len(candidate_list)
    _save_sniper_stored_index(idx)
    return get_playwright_proxy(proxy_url=candidate_list[idx])


def get_sniper_proxy() -> dict | None:
    """
    Returns a dedicated, verified healthy proxy for the Sniper (Playwright) and auto-login.
    Rotates across proxies so no single proxy is repeatedly loaded.
    Verifies the proxy against a live CROUS page to guarantee it is not rate-limited (429).
    """
    sniper_proxy_url = os.getenv("SNIPER_PROXY")
    if sniper_proxy_url:
        return get_playwright_proxy(proxy_url=sniper_proxy_url)

    candidate_list = _sniper_candidate_list()
    if not candidate_list:
        return None

    import urllib.request
    start_idx = _get_sniper_stored_index() % len(candidate_list)

    for i in range(len(candidate_list)):
        curr_idx = (start_idx + i) % len(candidate_list)
        p = candidate_list[curr_idx]
        try:
            req = urllib.request.Request(
                "https://trouverunlogement.lescrous.fr/tools/47/search",
                headers={"User-Agent": "Mozilla/5.0"}
            )
            opener = urllib.request.build_opener(urllib.request.ProxyHandler({"http": p, "https": p}))
            with opener.open(req, timeout=3.5) as resp:
                data = resp.read(256).decode("utf-8", errors="ignore")
                if resp.getcode() == 200 and "too many requests" not in data.lower():
                    _save_sniper_stored_index((curr_idx + 1) % len(candidate_list))
                    return get_playwright_proxy(proxy_url=p)
        except Exception:
            continue

    # Fallback to next candidate if all failed the full search test
    fallback_p = candidate_list[start_idx]
    _save_sniper_stored_index((start_idx + 1) % len(candidate_list))
    return get_playwright_proxy(proxy_url=fallback_p)


def get_playwright_proxy(proxy_url: str | None = None, rotate: bool = False) -> dict | None:
    """
    Format proxy dictionary for Playwright chromium.launch(proxy=...).
    """
    p_url = proxy_url or get_current_proxy(rotate=rotate)
    if not p_url:
        return None
    u = urlsplit(p_url)
    server = f"{u.scheme}://{u.hostname}"
    if u.port:
        server += f":{u.port}"
    cfg = {"server": server}
    if u.username:
        import urllib.parse
        cfg["username"] = urllib.parse.unquote(u.username)
    if u.password:
        import urllib.parse
        cfg["password"] = urllib.parse.unquote(u.password)
    return cfg


def get_auth_proxy() -> dict | None:
    """
    Returns a dedicated, verified proxy for authentication with CROUS and MesServices.
    Ensures both the housing site and the auth portal work before returning a candidate.

    Sources from the residential pool (load_residential_proxies()), not the scouter's
    datacenter pool -- login (Altcha challenge, cookies) is exactly the kind of flow
    where looking like a real human matters. The residential pool has no Oxylabs
    entries at all, so the AUTH_EXCLUDED_MARKERS filter that used to be needed here
    (Oxylabs gets a hard 403 on the .gouv.fr login host specifically) is moot now --
    left in place as a harmless defensive no-op in case that ever changes.
    """
    proxies = load_residential_proxies()
    candidates = [p for p in proxies if not any(m in p.lower() for m in AUTH_EXCLUDED_MARKERS)]
    if not candidates:
        logger.warning("No candidate proxies available for auth (all excluded or list empty).")
        return None

    import urllib.request

    start = _get_auth_stored_index() % len(candidates)

    for i in range(len(candidates)):
        idx = (start + i) % len(candidates)
        p = candidates[idx]

        u = urlsplit(p)
        host = u.hostname or ""
        port = str(u.port or "")
        host_port = f"{host}:{port}" if port else host

        opener = urllib.request.build_opener(urllib.request.ProxyHandler({"http": p, "https": p}))

        # Check 1: GET https://trouverunlogement.lescrous.fr/tools/47/search
        try:
            req1 = urllib.request.Request(
                "https://trouverunlogement.lescrous.fr/tools/47/search",
                headers={"User-Agent": "Mozilla/5.0"}
            )
            with opener.open(req1, timeout=AUTH_PROXY_CHECK_TIMEOUT) as resp:
                data = resp.read(256)
                data_str = data.decode("utf-8", errors="ignore") if isinstance(data, (bytes, bytearray)) else str(data)
                if resp.getcode() != 200 or "too many requests" in data_str.lower():
                    raise ValueError(f"HTTP {resp.getcode()}")
        except Exception as e:
            logger.warning(f"Auth proxy candidate {host_port} failed check for trouverunlogement.lescrous.fr: {type(e).__name__}")
            continue

        # Check 2: GET https://messervices.etudiant.gouv.fr/
        try:
            req2 = urllib.request.Request(
                "https://messervices.etudiant.gouv.fr/",
                headers={"User-Agent": "Mozilla/5.0"}
            )
            with opener.open(req2, timeout=AUTH_PROXY_CHECK_TIMEOUT) as resp:
                if resp.getcode() != 200:
                    raise ValueError(f"HTTP {resp.getcode()}")
        except Exception as e:
            logger.warning(f"Auth proxy candidate {host_port} failed check for messervices.etudiant.gouv.fr: {type(e).__name__}")
            continue

        _save_auth_stored_index((idx + 1) % len(candidates))
        logger.info(f"Auth proxy selected: {host}:{port}")
        return get_playwright_proxy(proxy_url=p)

    logger.error("All candidate auth proxies failed validation.")
    return None


# ==============================================================================
# Webshare sync (scouter's datacenter pool)
# ==============================================================================
# The Webshare plan's proxy list is pulled from the Webshare API into proxies_webshare.txt
# every 12 h, and within the hour after any 407 (Webshare's answer for "this address is no
# longer on your plan"). Why (2026-10-04): proxies.txt was a static file, so when Webshare
# auto-replaced 3 broken proxies on 2026-09-28 the bot kept using the removed addresses for 6
# days and never used the 3 replacements. proxies.txt keeps only hand-managed entries (Oxylabs).
# Off unless WEBSHARE_SYNC_ENABLED=true; needs WEBSHARE_API_KEY and WEBSHARE_DATACENTER_PLAN_ID
# (one API key covers the whole account -- the plan is chosen per call; without plan_id the
# API answers with a different plan).
WEBSHARE_PROXIES_FILENAME = "proxies_webshare.txt"
WEBSHARE_SYNC_STATE_FILENAME = ".webshare_sync.json"
WEBSHARE_SYNC_INTERVAL_SECONDS = 12 * 3600
WEBSHARE_SYNC_MIN_GAP_SECONDS = 3600      # never more than one API call per hour, even after failures
WEBSHARE_SYNC_MIN_KEEP_FRACTION = 0.5     # refuse a list less than half the size of the current one
WEBSHARE_API_URL = "https://proxy.webshare.io/api/v2/proxy/list/"


def _webshare_proxies_file() -> Path:
    # Next to PROXIES_FILE (not a fixed path), so anything that points PROXIES_FILE at a
    # temp dir -- every proxy test does -- never picks up the real synced list.
    return PROXIES_FILE.with_name(WEBSHARE_PROXIES_FILENAME)


def _webshare_sync_state_file() -> Path:
    return PROXIES_FILE.with_name(WEBSHARE_SYNC_STATE_FILENAME)


def webshare_sync_enabled() -> bool:
    return os.getenv("WEBSHARE_SYNC_ENABLED", "false").strip().lower() in ("true", "1", "yes")


def _read_sync_state() -> dict:
    try:
        data = json.loads(_webshare_sync_state_file().read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _write_sync_state(state: dict) -> None:
    path = _webshare_sync_state_file()
    temp_file = path.with_suffix(".tmp")
    try:
        temp_file.write_text(json.dumps(state, indent=2), encoding="utf-8")
        temp_file.replace(path)
    except Exception as e:
        logger.error(f"Failed to write {path}: {e}")


def get_webshare_sync_state() -> dict:
    """Read-only view of the sync bookkeeping (for /status)."""
    return _read_sync_state()


def request_webshare_sync(reason: str = "") -> None:
    """Ask for a sync as soon as the 1-hour minimum gap allows (e.g. a proxy answered 407)."""
    state = _read_sync_state()
    if not state.get("requested_at"):
        state["requested_at"] = time.time()
        state["requested_reason"] = (reason or "")[:200]
        _write_sync_state(state)


def webshare_sync_due(now: float | None = None) -> bool:
    if not webshare_sync_enabled():
        return False
    now = time.time() if now is None else now
    state = _read_sync_state()
    if now - float(state.get("last_attempt_at") or 0) < WEBSHARE_SYNC_MIN_GAP_SECONDS:
        return False
    if state.get("requested_at"):
        return True
    return now - float(state.get("last_success_at") or 0) >= WEBSHARE_SYNC_INTERVAL_SECONDS


def _fetch_webshare_plan_proxies(api_key: str, plan_id: str) -> list[dict]:
    """All proxies of one Webshare plan (mode=direct), following the API's pagination."""
    query = urllib.parse.urlencode({"mode": "direct", "page": 1, "page_size": 100, "plan_id": plan_id})
    url, results = f"{WEBSHARE_API_URL}?{query}", []
    for _ in range(50):  # 5000 proxies -- far beyond any plan; guards against a pagination loop
        req = urllib.request.Request(url, headers={"Authorization": f"Token {api_key}"})
        with urllib.request.urlopen(req, timeout=20) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        results.extend(data.get("results") or [])
        url = data.get("next")
        if not url:
            return results
    raise RuntimeError("Webshare API pagination did not end")


def sync_webshare_proxies(now: float | None = None, fetch=None) -> dict:
    """
    Pull the plan's current list and rewrite proxies_webshare.txt (valid proxies only).
    Safe by construction: on ANY failure -- API error, empty list, or a list less than half
    the size of the current one -- the existing file is kept untouched. Quarantine entries
    for proxies that left the pool are dropped; benches of proxies still in it are kept.

    Returns {"ok", "count", "added", "removed", "first_sync", "error", "consecutive_failures"}.
    """
    now = time.time() if now is None else now
    fetch = fetch or _fetch_webshare_plan_proxies
    state = _read_sync_state()
    state["last_attempt_at"] = now
    _write_sync_state(state)  # recorded first, so even a crash below can't cause hammering
    result = {"ok": False, "count": 0, "added": [], "removed": [], "first_sync": False,
              "error": None, "consecutive_failures": 0}

    path = _webshare_proxies_file()
    previous = {proxy_key(p) for p in _parse_proxies_file(path)}
    try:
        api_key = os.getenv("WEBSHARE_API_KEY", "").strip()
        plan_id = os.getenv("WEBSHARE_DATACENTER_PLAN_ID", "").strip()
        if not api_key or not plan_id:
            raise RuntimeError("WEBSHARE_API_KEY or WEBSHARE_DATACENTER_PLAN_ID missing")
        entries = []
        for r in fetch(api_key, plan_id):
            if not r.get("valid"):
                continue
            host, port, user, pwd = r.get("proxy_address"), r.get("port"), r.get("username"), r.get("password")
            if host and port and user and pwd:
                entries.append((str(host), int(port), str(user), str(pwd)))
        entries = sorted(set(entries))
        if not entries:
            raise RuntimeError("Webshare returned no valid proxies -- keeping the current list")
        if previous and len(entries) < WEBSHARE_SYNC_MIN_KEEP_FRACTION * len(previous):
            raise RuntimeError(f"Webshare returned only {len(entries)} valid proxies (current list: "
                               f"{len(previous)}) -- refusing to shrink the pool, keeping the current list")
        header = [
            "# AUTO-GENERATED from the Webshare API by proxy_manager.sync_webshare_proxies() -- do not edit.",
            f"# Plan {plan_id}, {len(entries)} valid proxies, synced {datetime.now(timezone.utc).isoformat()}",
            "# To keep a proxy out of rotation, bench it (proxy_manager.bench_proxy), don't delete it here.",
        ]
        temp_file = path.with_suffix(".tmp")
        temp_file.write_text("\n".join(header + [f"{h}:{p}:{u}:{w}" for h, p, u, w in entries]) + "\n",
                             encoding="utf-8")
        temp_file.replace(path)
        current = {f"{h}:{p}" for h, p, _, _ in entries}
        result.update(ok=True, count=len(entries), added=sorted(current - previous),
                      removed=sorted(previous - current), first_sync=not previous)

        pool_keys = {proxy_key(p) for p in load_proxies()}
        q = _read_quarantine_state()
        stale = [k for k in q if k not in pool_keys]
        if stale:
            for k in stale:
                del q[k]
            _write_quarantine_state(q)

        state.update(last_success_at=now, last_count=len(entries), consecutive_failures=0,
                     last_error=None, requested_at=None, requested_reason=None)
    except Exception as e:
        state["consecutive_failures"] = int(state.get("consecutive_failures") or 0) + 1
        state["last_error"] = f"{type(e).__name__}: {e}"[:300]
        result["error"] = state["last_error"]
        logger.warning(f"Webshare proxy sync failed (keeping the current list): {state['last_error']}")
    result["consecutive_failures"] = int(state.get("consecutive_failures") or 0)
    _write_sync_state(state)
    return result
